# Generated by Django 3.2.5 on 2021-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcodemodel',
            name='coolant_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='engine_load',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='fuel_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='intake_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='intake_pump',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='rpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errorcodemodel',
            name='throttle_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
