# Generated by Django 3.2.5 on 2021-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210729_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcodemodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='coolant_temp',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='engine_load',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='fuel_pressure',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='intake_pressure',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='intake_pump',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='rpm',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='speed',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='errorcodemodel',
            name='throttle_pos',
            field=models.DecimalField(decimal_places=4, max_digits=1000, null=True),
        ),
    ]
